networks:
  frontend:
    external: true

services:
  homepage:
    build: .
    restart: always
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lucascott-homepage.rule=Host(`www.lucascott.com`)"
      - "traefik.http.routers.lucascott-homepage.entrypoints=websecure"
      - "traefik.http.routers.lucascott-homepage.tls=true"
      - "traefik.http.routers.lucascott-homepage.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.lucascott-homepage.tls.domains[0].main=lucascott.com"
      - "traefik.http.routers.lucascott-homepage.tls.domains[1].main=www.lucascott.com"
      - "traefik.http.routers.lucascott-homepage.tls.domains[0].sans=*.lucascott.com"
